[package]
name = "docx_character_converter_rs"
version = "0.1.0"
authors = ["Nemo <nemoou@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"
zip = "0.5"
walkdir = "2"